// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elwitrxnyqxzyexfdhfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsd2l0cnhueXF4enlleGZkaGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTAyMDYsImV4cCI6MjA1OTU2NjIwNn0.fJAF3HYLgSZ4SrSuOI5e1kUSwFtJFEiLfIH7J7SS7xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);